# Generated by Django 5.1.1 on 2024-09-26 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_conta', models.CharField(choices=[('conta_corrente', 'Conta Corrente'), ('carteira', 'Carteira'), ('poupanca', 'Poupança'), ('investimentos', 'Investimentos'), ('outros', 'Outros...')], max_length=30)),
                ('saldo_inicial', models.IntegerField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
