# Generated by Django 5.1.1 on 2024-11-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_cartao_fatura_cartao_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
