# Generated by Django 5.1.1 on 2024-11-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fatura_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='valor_total',
        ),
    ]
