# Generated by Django 5.1.1 on 2024-11-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_fatura_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
