# Generated by Django 5.1.1 on 2024-11-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fatura_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='tipo_financeiro',
            field=models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita')], default='despesa', max_length=20),
        ),
    ]
